version: '2'
services:
  coldfusion:
    ports:
    - 0:8500
    - 0:5005
    environment:
    - password=vulhub
    - acceptEULA=YES
    build:
      context: .
      dockerfile: containers/coldfusion/Dockerfile
