version: '2'
services:
  rocketchat:
    command: "bash -c\n  \"for i in `seq 1 30`; do\n    node main.js &&\n    s=$$?\
      \ && break || s=$$?;\n    echo \\\"Tried $$i times. Waiting 5 secs...\\\";\n\
      \    sleep 5;\n  done; (exit $$s)\"\n"
    restart: unless-stopped
    environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
    - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    - MAIL_URL=smtp://smtp.email
    depends_on:
    - mongo
    ports:
    - 0:3000
    build:
      context: .
      dockerfile: containers/rocketchat/Dockerfile
  mongo:
    restart: unless-stopped
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
    - traefik.enable=false
    build:
      context: .
      dockerfile: containers/mongo/Dockerfile
  mongo-init-replica:
    command: "bash -c\n  \"for i in `seq 1 30`; do\n    mongo mongo/rocketchat --eval\
      \ \\\"\n      rs.initiate({\n        _id: 'rs0',\n        members: [ { _id:\
      \ 0, host: 'localhost:27017' } ]})\\\" &&\n    s=$$? && break || s=$$?;\n  \
      \  echo \\\"Tried $$i times. Waiting 5 secs...\\\";\n    sleep 5;\n  done; (exit\
      \ $$s)\"\n"
    depends_on:
    - mongo
    build:
      context: .
      dockerfile: containers/mongo-init-replica/Dockerfile
