version: '2'
services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: yapi
    build:
      context: .
      dockerfile: containers/mongo/Dockerfile
  web:
    ports:
    - 0:3000
    environment:
    - MONGO_ADDR=mongo:27017
    build:
      context: .
      dockerfile: containers/web/Dockerfile
