version: '3.5'
services:
  oap:
    command: bash bin/oap-service.sh
    build:
      context: .
      dockerfile: containers/oap/Dockerfile
  web:
    command: bash bin/web-server.sh
    depends_on:
    - oap
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    environment:
      COLLECTOR_RIBBON_LISTOFSERVERS: oap:12800
    build:
      context: .
      dockerfile: containers/web/Dockerfile
