services:
  nginx:
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    - target: 8081
      published: 0
      protocol: tcp
    - target: 8082
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
