services:
  node:
    build: .
    depends_on:
    - db
    ports:
    - target: 3000
      published: 0
      protocol: tcp
    volumes:
    - ./www:/usr/src/www
  db:
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=example
    build:
      context: .
      dockerfile: containers/db/Dockerfile
