services:
  weblogic:
    depends_on:
    - redis
    ports:
    - target: 7001
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/weblogic/Dockerfile
  redis:
    build:
      context: .
      dockerfile: containers/redis/Dockerfile
