services:
  struts2:
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    - target: 5005
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/struts2/Dockerfile
