version: '2.2'
services:
  jenkins:
    ports:
    - 0:50000
    - 0:8080
    - 0:5005
    init: true
    environment:
    - DEBUG=1
    build:
      context: .
      dockerfile: containers/jenkins/Dockerfile
