version: '2'
services:
  kibana:
    depends_on:
    - elasticsearch
    ports:
    - 0:5601
    build:
      context: .
      dockerfile: containers/kibana/Dockerfile
  elasticsearch:
    build:
      context: .
      dockerfile: containers/elasticsearch/Dockerfile
