version: '2'
services:
  web:
    build: .
    ports:
    - 0:8000
    depends_on:
    - db
  db:
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=cve
    build:
      context: .
      dockerfile: containers/db/Dockerfile
