version: '3'
services:
  web:
    entrypoint:
    - bash
    - /docker-entrypoint.sh
    depends_on:
    - db
    ports:
    - target: 80
      published: 0
      protocol: tcp
    environment:
    - TIKI_DB_DRIVER=pdo
    - TIKI_DB_HOST=db
    - TIKI_DB_USER=root
    - TIKI_DB_PASS=root
    - TIKI_DB_NAME=tikiwiki
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=tikiwiki
    ports:
    - target: 3306
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/db/Dockerfile
