services:
  web:
    ports:
    - target: 3000
      published: 0
      protocol: tcp
    - target: 22
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
