version: '2'
services:
  web:
    environment:
    - INFLUXDB_HTTP_AUTH_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin
    - INFLUXDB_DB=sample
    ports:
    - 0:8086
    build:
      context: .
      dockerfile: containers/web/Dockerfile
