version: '2'
services:
  redis:
    ports:
    - 0:6379
    build:
      context: .
      dockerfile: containers/redis/Dockerfile
  celery:
    command: celery -A tasks worker -l debug
    links:
    - redis
    environment:
      CELERY_BROKER_URL: redis://redis/0
    build:
      context: .
      dockerfile: containers/celery/Dockerfile
