services:
  namesrv:
    ports:
    - target: 9876
      published: 0
      protocol: tcp
    - target: 5005
      published: 0
      protocol: tcp
    command:
    - mqnamesrv
    build:
      context: .
      dockerfile: containers/namesrv/Dockerfile
  broker:
    ports:
    - target: 10911
      published: 0
      protocol: tcp
    command:
    - mqbroker
    - -n
    - namesrv:9876
    - --enable-proxy
    build:
      context: .
      dockerfile: containers/broker/Dockerfile
