services:
  aiohttp-app:
    container_name: aiohttp
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/aiohttp-app/Dockerfile
