services:
  solr:
    ports:
    - target: 8983
      published: 0
      protocol: tcp
    - target: 5005
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/solr/Dockerfile
