services:
  web:
    ports:
    - target: 80
      published: 0
      protocol: tcp
    depends_on:
    - db
    entrypoint:
    - bash
    - /entrypoint.sh
    command: apache2-foreground
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cacti
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - target: 3306
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/db/Dockerfile
