version: '2'
services:
  web:
    ports:
    - 0:8111
    - 0:5005
    environment:
    - TEAMCITY_SERVER_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    build:
      context: .
      dockerfile: containers/web/Dockerfile
