version: '2'
services:
  web:
    ports:
    - 0:8000
    depends_on:
    - db
    entrypoint:
    - bash
    - /docker-entrypoint.sh
    command:
    - python
    - app.py
    - runserver
    - 0.0.0.0:8000
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CVE_2022_34265
    build:
      context: .
      dockerfile: containers/db/Dockerfile
