services:
  jira:
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    links:
    - smtpd
    build:
      context: .
      dockerfile: containers/jira/Dockerfile
  smtpd:
    build:
      context: .
      dockerfile: Dockerfile.smtpd
