version: '2'
services:
  nginx:
    depends_on:
    - php
    ports:
    - 0:80
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
  php:
    build:
      context: .
      dockerfile: containers/php/Dockerfile
