version: '2'
services:
  web:
    ports:
    - 0:80
    depends_on:
    - mysql
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  mysql:
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
