version: '2'
services:
  web:
    ports:
    - 0:8090
    depends_on:
    - db
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=confluence
    build:
      context: .
      dockerfile: containers/db/Dockerfile
