services:
  web:
    ports:
    - target: 3000
      published: 0
      protocol: tcp
    environment:
    - NODE_ENV=production
    build:
      context: .
      dockerfile: containers/web/Dockerfile
