services:
  nginx:
    depends_on:
    - php
    ports:
    - target: 80
      published: 0
      protocol: tcp
    - target: 443
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
  php:
    command: /bin/sh /var/www/start.sh
    build:
      context: .
      dockerfile: containers/php/Dockerfile
