services:
  web:
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
