version: '2'
services:
  web:
    build: .
    ports:
    - 0:8000
    depends_on:
    - db
    restart: always
  db:
    restart: always
    build:
      context: .
      dockerfile: containers/db/Dockerfile
