services:
  web:
    depends_on:
    - mongo
    ports:
    - target: 8081
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  mongo:
    build:
      context: .
      dockerfile: containers/mongo/Dockerfile
