version: '2'
services:
  web:
    ports:
    - 0:80
    depends_on:
    - db
    entrypoint:
    - bash
    - /entrypoint.sh
    command: apache2-foreground
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cacti
    build:
      context: .
      dockerfile: containers/db/Dockerfile
