version: '2'
services:
  web:
    depends_on:
    - db
    environment:
    - MYSQL_HOST=db
    - MYSQL_PORT=3306
    - MYSQL_DB=jimureport
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    ports:
    - 0:8085
    - 0:5005
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=jimureport
    build:
      context: .
      dockerfile: containers/db/Dockerfile
