version: '2'
services:
  web:
    ports:
    - 0:9443
    - 0:8181
    environment:
    - UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9200
    depends_on:
    - elasticsearch
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  elasticsearch:
    environment:
    - cluster.name=contextElasticSearch
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    - bootstrap.memory_lock=true
    build:
      context: .
      dockerfile: containers/elasticsearch/Dockerfile
