version: '2'
services:
  web:
    depends_on:
    - db
    environment:
    - MYSQL_HOST=db
    - MYSQL_PORT=3306
    - MYSQL_DB=aj_report
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=root
    ports:
    - 0:9095
    - 0:5005
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=aj_report
    build:
      context: .
      dockerfile: containers/db/Dockerfile
