version: '3'
services:
  web:
    depends_on:
    - postgres
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    command: bash /startup.sh
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  postgres:
    environment:
    - POSTGRES_PASSWORD=vulhub
    - POSTGRES_DB=geoserver
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
