services:
  server:
    command: server
    depends_on:
    - mysql
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=zabbix
    ports:
    - target: 10051
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/server/Dockerfile
  agent:
    command: agent
    depends_on:
    - mysql
    - server
    environment:
    - ZBX_SRV_HOST=server
    - ZBX_SRV_HOST_ACT=server
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=zabbix
    build:
      context: .
      dockerfile: containers/agent/Dockerfile
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=zabbix
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
  web:
    depends_on:
    - server
    - mysql
    environment:
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=zabbix
    - ZBX_SRV_HOST=server
    - ZBX_SRV_PORT=10051
    ports:
    - target: 80
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
