version: '2'
services:
  ecshop27:
    depends_on:
    - mysql
    ports:
    - 0:80
    build:
      context: .
      dockerfile: containers/ecshop27/Dockerfile
  ecshop36:
    depends_on:
    - mysql
    ports:
    - 0:80
    build:
      context: .
      dockerfile: containers/ecshop36/Dockerfile
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
