services:
  nginx:
    ports:
    - target: 80
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
  php:
    command:
    - bash
    - -c
    - mkdir -p /var/www/html/uploadfiles && chown -R www-data:www-data /var/www/html/uploadfiles
      && php-fpm
    build:
      context: .
      dockerfile: containers/php/Dockerfile
