version: '2'
services:
  web:
    ports:
    - 0:80
    depends_on:
    - db
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=cmsms
    build:
      context: .
      dockerfile: containers/db/Dockerfile
