services:
  kibana:
    depends_on:
    - elasticsearch
    ports:
    - target: 5601
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/kibana/Dockerfile
  elasticsearch:
    environment:
    - discovery.type=single-node
    build:
      context: .
      dockerfile: containers/elasticsearch/Dockerfile
