version: '2'
services:
  nacos:
    container_name: nacos-standalone-mysql
    env_file:
    - ./env/nacos-standlone-mysql.env
    ports:
    - 0:8848
    - 0:9848
    - 0:9555
    depends_on:
    - mysql
    restart: on-failure
    build:
      context: .
      dockerfile: containers/nacos/Dockerfile
  mysql:
    container_name: mysql
    env_file:
    - ./env/mysql.env
    ports:
    - 0:3306
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
