version: '2'
services:
  web:
    depends_on:
    - mysql
    environment:
    - JOOMLA_DB_HOST=mysql
    - JOOMLA_DB_PORT=3306
    - JOOMLA_DB_USER=root
    - JOOMLA_DB_PASSWORD=vulhub
    - JOOMLA_DB_NAME=joomla
    ports:
    - 0:80
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=vulhub
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
