services:
  web:
    depends_on:
    - db
    ports:
    - target: 80
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=craftcms
    build:
      context: .
      dockerfile: containers/db/Dockerfile
