version: '2'
services:
  web:
    ports:
    - 0:80
    depends_on:
    - db
    - redis
    entrypoint:
    - bash
    - /entrypoint.sh
    command: apache2-foreground
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=v2board
    build:
      context: .
      dockerfile: containers/db/Dockerfile
  redis:
    build:
      context: .
      dockerfile: containers/redis/Dockerfile
