services:
  hertzbeat:
    ports:
    - target: 1157
      published: 0
      protocol: tcp
    - target: 5005
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/hertzbeat/Dockerfile
