version: '2'
services:
  web:
    depends_on:
    - mysql
    environment:
    - WORDPRESS_DB_HOST=mysql:3306
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_PASSWORD=root
    - WORDPRESS_DB_NAME=wordpress
    ports:
    - 0:80
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  mysql:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
