version: '2'
services:
  web:
    build: .
    ports:
    - 0:8000
    depends_on:
    - db
  db:
    environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=cve
    build:
      context: .
      dockerfile: containers/db/Dockerfile
