services:
  rocketmq:
    ports:
    - target: 10911
      published: 0
      protocol: tcp
    - target: 5005
      published: 0
      protocol: tcp
    command:
    - mqbroker
    - -n
    - localhost:9876
    - --enable-proxy
    build:
      context: .
      dockerfile: containers/rocketmq/Dockerfile
