version: '2'
services:
  web:
    ports:
    - 0:8000
    depends_on:
    - db
    environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    build:
      context: .
      dockerfile: containers/web/Dockerfile
  db:
    environment:
    - POSTGRES_PASSWORD=postgres
    build:
      context: .
      dockerfile: containers/db/Dockerfile
