services:
  apache:
    command: /bin/sh /var/www/start.sh
    ports:
    - target: 80
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/apache/Dockerfile
