version: '3'
services:
  node1:
    environment:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin-vulhub
    command:
    - minio
    - server
    - --console-address
    - :9001
    - http://node1:9000/mnt/data1
    - http://node2:9000/mnt/data2
    - http://node3:9000/mnt/data3
    ports:
    - target: 9000
      published: 0
      protocol: tcp
    - target: 9001
      published: 0
      protocol: tcp
    hostname: node1
    build:
      context: .
      dockerfile: containers/node1/Dockerfile
  node2:
    environment:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin-vulhub
    command:
    - minio
    - server
    - http://node1:9000/mnt/data1
    - http://node2:9000/mnt/data2
    - http://node3:9000/mnt/data3
    hostname: node2
    build:
      context: .
      dockerfile: containers/node2/Dockerfile
  node3:
    environment:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin-vulhub
    command:
    - minio
    - server
    - http://node1:9000/mnt/data1
    - http://node2:9000/mnt/data2
    - http://node3:9000/mnt/data3
    hostname: node3
    build:
      context: .
      dockerfile: containers/node3/Dockerfile
