services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    depends_on:
    - php
    ports:
    - target: 80
      published: 0
      protocol: tcp
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
