services:
  web:
    command: php -t /var/www/html -S 0.0.0.0:8080
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
