services:
  discuz:
    depends_on:
    - db
    ports:
    - target: 80
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/discuz/Dockerfile
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discuz
    build:
      context: .
      dockerfile: containers/db/Dockerfile
