version: '2'
services:
  apisix:
    depends_on:
    - etcd
    ports:
    - 0:9080
    - 0:9091
    - 0:9443
    build:
      context: .
      dockerfile: containers/apisix/Dockerfile
  dashboard:
    depends_on:
    - etcd
    ports:
    - 0:9000
    build:
      context: .
      dockerfile: containers/dashboard/Dockerfile
  etcd:
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ports:
    - 0:2379
    build:
      context: .
      dockerfile: containers/etcd/Dockerfile
