version: '2.4'
services:
  core:
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
    env_file: config.env
    ports:
    - 0:80
    - 0:2222
    networks:
    - jumpnet
    build:
      context: .
      dockerfile: containers/core/Dockerfile
  mysql:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file: config.env
    networks:
    - jumpnet
    build:
      context: .
      dockerfile: containers/mysql/Dockerfile
  redis:
    command:
    - /bin/sh
    - -c
    - redis-server --requirepass $$REDIS_PASSWORD --loglevel warning --maxmemory-policy
      allkeys-lru
    env_file: config.env
    networks:
    - jumpnet
    build:
      context: .
      dockerfile: containers/redis/Dockerfile
networks:
  jumpnet: null
