services:
  namenode:
    environment:
    - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
    - CLUSTER_NAME=vulhub
    - HDFS_CONF_dfs_replication=1
    command: /namenode.sh
    build:
      context: .
      dockerfile: containers/namenode/Dockerfile
  datanode:
    environment:
    - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - CLUSTER_NAME=vulhub
    - HDFS_CONF_dfs_replication=1
    command: /datanode.sh
    build:
      context: .
      dockerfile: containers/datanode/Dockerfile
  resourcemanager:
    environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_log___aggregation___enable=true
    command: /resourcemanager.sh
    ports:
    - target: 8088
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/resourcemanager/Dockerfile
  nodemanager:
    environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    - YARN_CONF_yarn_log___aggregation___enable=true
    - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    command: /nodemanager.sh
    build:
      context: .
      dockerfile: containers/nodemanager/Dockerfile
