services:
  web:
    command: mini_httpd -p 8080 -u www-data -h 0.0.0.0 -D -l /dev/stdout -v -T utf-8
    ports:
    - target: 8080
      published: 0
      protocol: tcp
    build:
      context: .
      dockerfile: containers/web/Dockerfile
